include: package:lint/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    prefer_single_quotes: true
    lines_longer_than_80_chars: true
    use_setters_to_change_properties: false
