name: vercel_dart
description: A utility library for writing serverless functions in the Vercel Dart Runtime.
version: 1.0.0
repository: https://github.com/frencojobs/vercel-dart

publish_to: none # until the PR #24 is merged

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  # aws_lambda_dart_runtime: ^1.0.3+2
  aws_lambda_dart_runtime:
    git: https://github.com/frencojobs/aws-lambda-dart-runtime.git
  json_annotation: ^3.1.1
  shelf: ^0.7.9

dev_dependencies:
  build_runner: ^1.11.1
  import_sorter: ^4.4.1
  json_serializable: ^3.5.1
  lint: ^1.3.0
  test: ^1.14.4

scripts:
  format: dartfmt -w .
  sort:
    imports: pub run import_sorter:main *

import_sorter:
  comments: false
